# Generated by Django 4.1.5 on 2023-01-03 23:40

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedimage",
            name="image",
            field=models.ImageField(
                upload_to=gallery.models.sanitize_filename,
                verbose_name="Uploaded image",
            ),
        ),
    ]
