# Generated by Django 4.1.5 on 2023-01-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_alter_uploadedimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="heigth",
            field=models.IntegerField(default="260"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="name",
            field=models.CharField(default='name', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="width",
            field=models.IntegerField(default=260),
            preserve_default=False,
        ),
    ]
